"""Validate local or S3 ModelOps outputs generated by the incremental overlay."""

from __future__ import annotations

import argparse
import json
from io import BytesIO
from pathlib import Path

import boto3
import pandas as pd

REQUIRED_FORECAST_COLS = {"shop_id", "shop_name", "item_id", "item_name", "prediction"}
REQUIRED_RUN_COLS = {"model_id", "model_name", "mae", "rmse", "is_champion"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bucket", default=None)
    parser.add_argument("--local-root", type=Path, default=Path("modelops_outputs"))
    parser.add_argument("--latest-prefix", default="modelops/latest")
    parser.add_argument("--registry-prefix", default="modelops/registry")
    return parser.parse_args()


def read_parquet(bucket: str | None, local_root: Path, key: str) -> pd.DataFrame:
    if bucket:
        obj = boto3.client("s3").get_object(Bucket=bucket, Key=key)
        return pd.read_parquet(BytesIO(obj["Body"].read()))
    rel = key.replace("modelops/latest/", "")
    return pd.read_parquet(local_root / rel)


def read_csv(bucket: str | None, local_root: Path, key: str) -> pd.DataFrame:
    if bucket:
        obj = boto3.client("s3").get_object(Bucket=bucket, Key=key)
        return pd.read_csv(obj["Body"])
    rel = key.replace("modelops/registry/", "registry/").replace("modelops/latest/", "")
    return pd.read_csv(local_root / rel)


def read_json(bucket: str | None, local_root: Path, key: str) -> dict:
    if bucket:
        obj = boto3.client("s3").get_object(Bucket=bucket, Key=key)
        return json.loads(obj["Body"].read().decode("utf-8"))
    rel = key.replace("modelops/registry/", "registry/").replace("modelops/latest/", "")
    return json.loads((local_root / rel).read_text(encoding="utf-8"))


def main() -> None:
    args = parse_args()
    forecast = read_parquet(args.bucket, args.local_root, f"{args.latest_prefix}/predictions/forecast_detail.parquet")
    missing_forecast = REQUIRED_FORECAST_COLS - set(forecast.columns)
    if missing_forecast:
        raise SystemExit(f"forecast_detail missing columns: {sorted(missing_forecast)}")
    runs = read_csv(args.bucket, args.local_root, f"{args.registry_prefix}/model_runs.csv")
    missing_runs = REQUIRED_RUN_COLS - set(runs.columns)
    if missing_runs:
        raise SystemExit(f"model_runs missing columns: {sorted(missing_runs)}")
    champion = read_json(args.bucket, args.local_root, f"{args.registry_prefix}/champion.json")
    print("VALIDATION OK")
    print("forecast_detail", forecast.shape)
    print("model_runs", runs[[c for c in ["model_id", "model_name", "mae", "rmse", "is_champion"] if c in runs.columns]].to_string(index=False))
    print("champion", champion.get("model_id"), champion.get("model_name"), "mae=", champion.get("mae"))


if __name__ == "__main__":
    main()
